services:
  backend-api:
    environment:
    # the .env file supersedes these variable
      - APP_NAME=ELO@AIC Image Semantic Search
      - gpt_translate_model=gpt-4o-mini
      - ocr_path=/data/text_extracted
      - object_counting_path=/data/Object_Counting_vector_np
      # empty string to deactivate
      - asr_path=
      - blip2_embs_path=
      - clip_H_embs_path=
      - clip_bigG_embs_path=
      - clip_B32_embs_path=/data/clip-features-vit-b32

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

    volumes:
      - ./src:/src      
      - ./data:/data

      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/torch:/root/.cache/torch
      - ~/.cache/clip:/root/.cache/clip

      # config file (contains the openai api key)
      # - ./.env:/.env

    networks:
      - project_network
    entrypoint: >
      conda run --no-capture-output -n py311 python -u -m uvicorn src.main:app --host 0.0.0.0 --port 8000

  # frontend:
  #   image: aic_be:latest
  #   ports:
  #     - 8501:8501
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - backend-api
  #   networks:
  #     - project_network
networks:
  project_network:
