name: py311
channels:
- conda-forge
- pytorch
# - nvidia
dependencies:
- python=3.11
- gdown=5.2.0
- pytorch=2.3.1
- torchaudio=2.3.1
- torchvision=0.18.1
- cpuonly=2.0

- faiss-cpu=1.8.0
# - faiss-gpu=1.8.0

- open-clip-torch=2.26.1
- tqdm=4.66.5
- numpy=1.26.4
- pillow=10.4.0

# - matplotlib
- fastapi=0.112.1
- pydantic-settings=2.4.0
- fuzzywuzzy=0.18.0
- joblib=1.4.2
- openai=1.42.0

- pip:
  - salesforce-lavis==1.0.2
