name: py311
channels:
- pytorch
- conda-forge
- anaconda
dependencies:
- python=3.11.9
- pip=24.2
- gdown=5.2.0

- pytorch=2.5.0
- torchaudio=2.5.0
- torchvision=0.20.0
- cpuonly=2.0

- faiss-cpu=1.8.0
# - faiss-gpu=1.8.0
- pandas=2.2.3

- timm
- open-clip-torch
- tqdm=4.66.5
- numpy=1.26.4
- pillow=10.4.0
- transformers

# - matplotlib
- fastapi=0.112.1
- pydantic-settings=2.4.0
- fuzzywuzzy=0.18.0
- joblib=1.4.2
- openai

- openblas
- openmp 
- cmake

- pip:
  # - salesforce-lavis==1.0.2
  # - timm==1.0.9
  - elasticsearch==8.15.0
  # - numpy==1.26.4
  - git+https://github.com/Museum7432/ftsearch.git

