name: py311gpu
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- python=3.11.9
- pip=24.2
- gdown=5.2.0

- pytorch=2.3.0
- torchaudio=2.3.0
- torchvision=0.18.0
- pytorch-cuda=12.1

- faiss-cpu=1.8.0
# - faiss-gpu=1.8.0

- timm=1.0.9
- open-clip-torch=2.26.1
- tqdm=4.66.5
- numpy=1.26.4
- pillow=10.4.0

# - matplotlib
- fastapi=0.112.1
- pydantic-settings=2.4.0
- fuzzywuzzy=0.18.0
- joblib=1.4.2
- openai
# - openblas
- openmp 
- cmake

- pip:
  - salesforce-lavis==1.0.2
  - elasticsearch==8.15.0
  - numpy==1.26.4
  - git+https://github.com/Museum7432/ftsearch.git
